name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build for Linux
      run: |
        $env:GOOS = "linux"
        $env:GOARCH = "amd64"
        go build -o ./output/goflappy-linux-amd64 ./...

    - name: Build for MacOS
      run: |
        $env:GOOS = "darwin"
        $env:GOARCH = "amd64"
        go build -o ./output/goflappy-darwin-amd64 ./...

    - name: Build for Windows
      run: |
        $env:GOOS = "windows"
        $env:GOARCH = "amd64"
        go build -o ./output/goflappy-windows-amd64.exe ./...

    - name: Test
      run: go test -v ./...

    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: goflappy-linux-amd64
        path: ./output/goflappy-linux-amd64

    - name: Upload artifact (MacOS)
      uses: actions/upload-artifact@v2
      with:
        name: goflappy-darwin-amd64
        path: ./output/goflappy-darwin-amd64

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: goflappy-windows-amd64
        path: ./output/goflappy-windows-amd64.exe
