name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Include Assets
      run: |
        mkdir -p ./output
        cp -r ./assets ./output/assets

    - name: Install Go modules
      run: go mod download

    - name: Build
      run: go build -v -o ./output/GoFlappy .

    # - name: Build for Windows
    #   run: |
    #     $env:GOOS = "windows"
    #     $env:GOARCH = "amd64"
    #     go build -o ./output/GoFlappy-windows-amd64.exe ./...

    - name: Test
      run: go test -v ./...

    # - name: Upload artifact (Windows)
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: GoFlappy-windows-amd64
    #     path: ./output/GoFlappy-windows-amd64.exe

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: GoFlappy(Windows).exe
        path: ./output/
