name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install Go modules
      run: go mod download

    - name: Build
      run: go build -v -o ./output/GoFlappy .

    - name: Build for Linux
      run: |
        $env:GOOS = "linux"
        $env:GOARCH = "amd64"
        go build -o ./output/GoFlappy-linux-amd64 ./...

    - name: Build for MacOS
      run: |
        $env:GOOS = "darwin"
        $env:GOARCH = "amd64"
        go build -o ./output/GoFlappy-darwin-amd64 ./...

    - name: Build for Windows
      run: |
        $env:GOOS = "windows"
        $env:GOARCH = "amd64"
        go build -o ./output/GoFlappy-windows-amd64.exe ./...

    - name: Test
      run: go test -v ./...

    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: GoFlappy-linux-amd64
        path: ./output/GoFlappy-linux-amd64

    - name: Upload artifact (MacOS)
      uses: actions/upload-artifact@v2
      with:
        name: GoFlappy-darwin-amd64
        path: ./output/GoFlappy-darwin-amd64

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: GoFlappy-windows-amd64
        path: ./output/GoFlappy-windows-amd64.exe
