name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Include Assets
      run: |
        mkdir -p ./output
        cp -r ./assets ./output/assets

    - name: Install Go modules
      run: go mod download

    - name: Build for Windows
      run: |
        GOOS=windows go build -v -o ./output/GoFlappy-windows.exe .

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: GoFlappy-windows
        path: ./output/GoFlappy-windows.exe

    - name: Build for Linux
      run: |
        GOOS=linux go build -v -o ./output/GoFlappy-linux .

    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: GoFlappy-linux
        path: ./output/GoFlappy-linux

    - name: Build for MacOS
      run: |
        GOOS=darwin go build -v -o ./output/GoFlappy-darwin .

    - name: Upload artifact (MacOS)
      uses: actions/upload-artifact@v2
      with:
        name: GoFlappy-darwin
        path: ./output/GoFlappy-darwin

    - name: Test
      run: go test -v ./...
